export const IPO_DATA = [
  {
    id: 1,
    logo: '/nova-agritech-logo.png',
    name: 'Nova Agritech Ltd.',
    priceBand: 'Rs 39 - 41',
    openDate: '2024-01-22',
    closeDate: '2024-01-24',
    lotSize: 365,
    issueSize: '143.81 Cr.',
    issueType: 'Book Built',
    listingDate: '2024-01-30',
    sector: 'Agriculture',
    rhpLink: '#',
    drhpLink: '#',
  },
  {
    id: 2,
    logo: '/epack-durable-logo.png',
    name: 'EPACK Durable Ltd.',
    priceBand: 'Rs 218 - 230',
    openDate: '2024-01-19',
    closeDate: '2024-01-23',
    lotSize: 65,
    issueSize: '640.05 Cr.',
    issueType: 'Book Built',
    listingDate: '2024-01-29',
    sector: 'Consumer Durables',
    rhpLink: '#',
    drhpLink: '#',
  },
  {
    id: 3,
    logo: '/rk-swamy-logo.png',
    name: 'RK Swamy Ltd.',
    priceBand: 'Not Issued',
    openDate: 'Not Issued',
    closeDate: 'Not Issued',
    lotSize: 'Not Issued',
    issueSize: 'Not Issued',
    issueType: 'Book Built',
    listingDate: 'Not Issued',
    sector: 'Advertising',
    rhpLink: '#',
    drhpLink: '#',
  },
  {
    id: 4,
    logo: '/innova-captab-logo.png',
    name: 'Innova Captab Ltd.',
    priceBand: 'Rs 426 - 448',
    openDate: '2024-01-10',
    closeDate: '2024-01-12',
    lotSize: 33,
    issueSize: '570 Cr.',
    issueType: 'Book Built',
    listingDate: '2024-01-18',
    sector: 'Pharmaceuticals',
    rhpLink: '#',
    drhpLink: '#',
  },
  {
    id: 5,
    logo: '/medi-assist-logo.png',
    name: 'Medi Assist Healthcare Services Ltd.',
    priceBand: 'Rs 397 - 418',
    openDate: '2024-01-15',
    closeDate: '2024-01-17',
    lotSize: 35,
    issueSize: '1,171.58 Cr.',
    issueType: 'Book Built',
    listingDate: '2024-01-23',
    sector: 'Healthcare',
    rhpLink: '#',
    drhpLink: '#',
  },
  {
    id: 6,
    logo: '/zomato-logo.png',
    name: 'Zomato Ltd.',
    priceBand: 'Rs 72 - 76',
    openDate: '2024-02-01',
    closeDate: '2024-02-03',
    lotSize: 195,
    issueSize: '9,375 Cr.',
    issueType: 'Book Built',
    listingDate: '2024-02-10',
    sector: 'Food Tech',
    rhpLink: '#',
    drhpLink: '#',
  },
  {
    id: 7,
    logo: '/ola-electric-mobility-logo.png',
    name: 'OLA Electric Mobility Ltd.',
    priceBand: 'Not Issued',
    openDate: 'Not Issued',
    closeDate: 'Not Issued',
    lotSize: 'Not Issued',
    issueSize: '5,500 Cr.',
    issueType: 'Book Built',
    listingDate: 'Not Issued',
    sector: 'Automobile',
    rhpLink: '#',
    drhpLink: '#',
  },
  {
    id: 8,
    logo: '/one-mobikwik-logo.png',
    name: 'One Mobikwik Systems Ltd.',
    priceBand: 'Not Issued',
    openDate: 'Not Issued',
    closeDate: 'Not Issued',
    lotSize: 'Not Issued',
    issueSize: '1,900 Cr.',
    issueType: 'Book Built',
    listingDate: 'Not Issued',
    sector: 'Fintech',
    rhpLink: '#',
    drhpLink: '#',
  },
  {
    id: 9,
    logo: '/ixigo-logo.png',
    name: 'Le Travenues Technology (Ixigo)',
    priceBand: 'Not Issued',
    openDate: 'Not Issued',
    closeDate: 'Not Issued',
    lotSize: 'Not Issued',
    issueSize: '1,600 Cr.',
    issueType: 'Book Built',
    listingDate: 'Not Issued',
    sector: 'Travel',
    rhpLink: '#',
    drhpLink: '#',
  },
  {
    id: 10,
    logo: '/cmr-green-tech-logo.png',
    name: 'CMR Green Technologies Ltd.',
    priceBand: 'Not Issued',
    openDate: 'Not Issued',
    closeDate: 'Not Issued',
    lotSize: 'Not Issued',
    issueSize: 'Not Issued',
    issueType: 'Book Built',
    listingDate: 'Not Issued',
    sector: 'Recycling',
    rhpLink: '#',
    drhpLink: '#',
  },
]; 